pull_request_rules:
  - name: SSTI test
    conditions:
      - base=main
    actions:
      comment:
        message: |
          Result: {{7*7}}
          Author: {{author}}
          Branch: {{head}}
